/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf -t 
Author: WalidEH (https://sketchfab.com/WalidEH)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/luffys-hat-straw-hat-b809899671d043d3bbe76d0505ab1d88
Title: Luffy's Hat (Straw Hat)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    red_thing_Material001_0: THREE.Mesh
    Straw_Hat_Material002_0: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function StrawHat(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene.gltf')  as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Straw_Hat_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.red_thing_Material001_0.geometry} material={materials['Material.001']} position={[-0.003, 0, 0.063]} scale={[1, 1, 1.76]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
